TASK=SST2
SUFFIX=sparsity0.60
EX_CATE=CoFi_RoBERTa_LoRA
PRUNING_TYPE=structured_heads+structured_mlp+hidden+layer
SPARSITY=0.60
DISTILL_LAYER_LOSS_ALPHA=0.9
DISTILL_CE_LOSS_ALPHA=0.1
LAYER_DISTILL_VERSION=4
SPARSITY_EPSILON=0.01
DISTILLATION_PATH=/mmfs1/home/bowen98/projects/AdaptPruning/output/roberta-base_sst2_full/epoch60/bz32/best_model

bash scripts/run_CoFi_roberta_lora_noffn.sh $TASK $SUFFIX $EX_CATE $PRUNING_TYPE $SPARSITY $DISTILLATION_PATH $DISTILL_LAYER_LOSS_ALPHA $DISTILL_CE_LOSS_ALPHA $LAYER_DISTILL_VERSION $SPARSITY_EPSILON